{% set name = "include-what-you-use" %}
{% set version = "0.22" %}
{% set llvm_version = "18.*" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 34c7636da2abe7b86580b53b762f5269e71efff460f24f17d5913c56eb99cb7c

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - python
    - make
  host:
    - clangdev {{ llvm_version }}
    - llvmdev {{ llvm_version }}
    - llvm {{ llvm_version }}
    - libclang-cpp {{ llvm_version }}
    - lld {{ llvm_version }}
test:
  requires:
    - python >=3.8
  commands:
    - {{ name }} --version
    - {{ name }} --help
    - iwyu_tool.py --help
    - fix_includes.py --help


about:
  home: https://include-what-you-use.org
  summary: 'A tool for use with clang to analyze #includes in C and C++ source files'
  description: |
    "Include what you use" means this: for every symbol (type, function, variable, or macro)
    that you use in foo.cc (or foo.cpp), either foo.cc or foo.h should include a .h file that
    exports the declaration of that symbol. (Similarly, for foo_test.cc, either foo_test.cc or foo.h
    should do the including.) Obviously symbols defined in foo.cc itself are excluded from this requirement.
  license: NCSA  # University of Illinois/NCSA Open Source
  license_family: OTHER  # NCSA
  license_file: LICENSE.TXT
  doc_url: https://include-what-you-use.org
  dev_url: https://github.com/include-what-you-use/include-what-you-use

extra:
  recipe-maintainers:
    - xmnlab
    - xylar
    - galexite
